FROM golang:1.18.1-alpine as builder
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /main main.go


FROM scratch
WORKDIR /bin
COPY db.csv .
COPY db.json .
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder main ./main
ENTRYPOINT ["/bin/main"]